// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGw4XlMGVnFxe8qU4TATe3aK_a7vBDRlk',
    appId: '1:653897955390:web:bb74e728b3f14f8d73f96f',
    messagingSenderId: '653897955390',
    projectId: 'panorama-kg',
    authDomain: 'panorama-kg.firebaseapp.com',
    storageBucket: 'panorama-kg.firebasestorage.app',
    measurementId: 'G-G4W6B487M4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO1KogBLkgwJlBcz90a0GbgH_VcLhb2HU',
    appId: '1:653897955390:android:c60b687e37d837e673f96f',
    messagingSenderId: '653897955390',
    projectId: 'panorama-kg',
    storageBucket: 'panorama-kg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2MAjY_6CdIIBlR5u_zNwTjrJmxfhp5dc',
    appId: '1:653897955390:ios:394dcc09e2e4ed8973f96f',
    messagingSenderId: '653897955390',
    projectId: 'panorama-kg',
    storageBucket: 'panorama-kg.firebasestorage.app',
    iosBundleId: 'kg.panorama.panoramaSales',
  );
}
